[Documentation] Fix project referred to as example
makeopensource/devU-api pull request #19
Opened 2022-10-05 23:18 UTC by WeirdAlex03

## Proposed changes
--------------------
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

Fixes makeopensource/devU-api#18

## Types of changes
--------------------
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist
--------------------
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code._

- [x] My changeset covers only what is described above (no extraneous changes)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged downstream

## Further comments
--------------------
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-10-12 21:27 UTC, emilkovacev requested changes
Other than this change, this PR looks good

2022-10-12 21:27 UTC, emilkovacev commented on README.md
Can you capitalize line 12 of this file?

2022-10-12 21:58 UTC, jessehartloff approved these changes

2022-10-12 22:02 UTC, emilkovacev approved these changes

2022-10-19 20:41 UTC, jessehartloff approved these changes
Thank you for the clean up

2022-10-19 20:41 UTC, merged